### ISSUE TITLE
ImportError: No module named iTunesLibrary

### ISSUE THREAD

**Issue by reknoZ** [scholnicks/itunes-library#2]
Howdy,

I've just installed your library via
`pip install iTunesLibrary`

Then, I started python and tried the code on your page:
`from iTunesLibary import library`

And I got the error message:
`ImportError: No module named iTunesLibrary`

I tried `pip list` and it's listed there. I tried `pip search iTunes` and your library is listed and marked as installed.

I've uninstalled/re-installed numerous times. As standard user and as root. I can't get past the import line!

**Comment by scholnicks** [comment]
Python 2 or 3? I haven’t used it in a while; Spotify is now my main music
source.

-steve

**Comment by scholnicks** [comment]
I get the same issue using both Python 2 and Python 3. I'll look into it.

**Comment by scholnicks** [comment]
Version 1.1.2 has been uploaded to PyPi which fixes this error. 

Try:
from iTunesLibrary import library

**Comment by reknoZ** [comment]
Thanks! I installed it, the import statement works. now it's parsing my gigantic XML file. Fingers crossed.
