### ISSUE TITLE
Incorrectly parsing playlists

### ISSUE THREAD

**Issue by medcelerate** [scholnicks/itunes-library#3]
It appears that the playlist parsing is not functioning properly. When I attemt to use the methods instead of retrieving my playlists I get the follow:
```
b'Library': 190
b'Downloaded': 31
b'Music': 31
b'Podcasts': 710
b'Voice Memos': 29
```

I am also unable to get playlists as these higher level structures seem to be taking their place.

**Comment by scholnicks** [comment]
Arrghh.. I bet Apple changed the iTunes XML format again.  Also I don't use iTunes anymore; we've switched to Spotify. :) I'll look into this.

**Comment by scholnicks** [comment]
Cannot reproduce
